version: "3"
services:
    nginx:
        image: npnginx
        build:
            context: ./dockerfiles/nginx
            args:
                ALPINE_VERSION: ${ALPINE_VERSION}
                CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
                TZ: ${TZ}
        container_name: npnginx
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/conf.d:/etc/nginx/conf.d
            - ./log:/var/log/nginx
        ports:
            - "80:80"
        links:
            - testnginx

    testnginx:
        image: testnginx
        build:
            context: ./dockerfiles/nginx
            args:
                ALPINE_VERSION: ${ALPINE_VERSION}
                CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
                TZ: ${TZ}
        container_name: testnginx
        volumes:
            - ./conf/conf.d/test.com/nginx.conf:/etc/nginx/nginx.conf
            - ./log/test.com:/var/log/nginx
            - ./src:/var/www
        ports:
            - "8080:80"
        links:
            - php

    php:
        image: testphp
        build:
            context: ./dockerfiles/php
            args:
                ALPINE_VERSION: ${ALPINE_VERSION}
                CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
                TZ: ${TZ}
        container_name: testphp
        volumes:
            - ./conf/php.ini:/etc/php7/php.ini
            - ./conf/php-fpm.d:/etc/php7/php-fpm.d
            - ./src/test:/var/www/test
        ports:
            - "9732:9000"
